title:       MTC/ABAG Planning Portal
email:       lzorn@bayareametro.gov
description: Planning Portal for MTC/ABAG
repository:  BayAreaMetro/planning-portal

tagline:  'Bay Area Metro'
url:      http://bayareametro.github.io/planning-portal
shorturl: bayareametro.github.io
github_username: BayAreaMetro
twitter_username: MTCBATA

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink: pretty
